Def Struct carthdr                                  
 member userid$[8]      : Item 0                    
 member custid$[10]     : Item 8                   
 member po$[20]         : Item 18                  
 member shipdate$[8]    : Item 38                  
 member shipto$[6]      : Item 46                  
 member shiptoname$[30] : Item 52                  
 member shiptoaddr1$[30]: Item 82                  
 member shiptoaddr2$[30]: Item 112                
 member shiptoaddr3$[30]: Item 142  
 member shiptocity$[15] : Item 142
 member shiptostate$[2] : Item 157
 member shiptozip$[13]  : Item 159              
 member 1%,ordertype    : Item 172             
 member 2%,miscchargecode[9]    : Item 174          
 member 3%,misccharge[9]: Item 214          
 member 3%,miscchargecost[9]    : Item 274  
 member 3%,orderdiscount        : Item 334
 member 3%,pooverride           : Item 340
 member attn$[30]               : Item 346
 member 1%,terms              : Item 376
 member 1%,routing            : Item 378
 member shipcust$[6]	      : Item 380
 member 3%,ordernum	      : Item 386
 member headwh$[2]	      : Item 392
End Def                                                                             