Def Struct soInfo
  Member Whse$[2]
  Member Commodity$[20]
  Member Vendor$[50]
  Member Item$[30]
  Member Desc1$[30]
  Member Desc2$[30]
  Member SODate$[12]
  Member PO$[100]
  Member Qty$[150]
  Member POR$[150]
  Member PODate$[120]
  Member Avail$[50]
End Def

Def Struct coInfo
  Member WHSE$[2]
  Member Commodity$[20]
  Member Vendor$[50]
  Member Item$[30]
  Member Desc$[65]
  Member OldCost$[15]
  Member UOM$[4]
  Member NewCost$[15]
  Member Change$[15]
  Member EffDate$[12]
End Def
