Def Struct Lastprice
	Member LP$[12]		: Item 0
	Member 2%,LPDF		: Item 12
	Member 2%,LPC1[2]	: Item 16
	Member 3%,LPC2[2]	: Item 28
	Member 1%,LPC3[4]	: Item 46
	Member LP2$[84]		: Item 56
	Member 3%,LPC4[3]	: Item 140
	Member LPMT$[2]		: Item 164
	Member 1%,AI		: Item 166
	Member 3%,LPR[4]	: Item 168
	Member 2%,LPR1[3]	: Item 198
	Member 1%,LPEUN[2]	: Item 214
	Member 3%,LPUNF[6]	: Item 220
	Member 3%,PERM[1]	: Item 262
	Member 1%,LPWH		: Item 274
	Member 2%,LPC5[3]	: Item 276
	Member 2%,LPPCDATE	: Item 292
	Member 3%,LPLPERM	: Item 296
	Member 3%,LPCURR[1]	: Item 302
	Member 1%,LPCPT		: Item 314
	Member 2%,LPCSDT	: Item 316
	Member 2%,LPDEPT	: Item 320
	Member 3%,LPFPERM[1]	: Item 324
	Member 1%,PPPUSERID	: Item 336
	Member 3%,LPUNIT[1]	: Item 340
	Member 2%,PPPCID[1]	: Item 352
	Member ABLSUB$[12]	: Item 360
	Member 1%,CURRID        : Item 474 ! 
	Member 3%,CURRFACT      : Item 476 ! 
	Member Spare$[117]       : Item 482 ! 
End Def
